### ISSUE TITLE
Is fail to read single uasset DataTable?

### ISSUE THREAD

**Issue by zbx911** [MinshuG/pyUE4Parse#1]
up

**Comment by MinshuG** [comment]
what?

**Comment by MinshuG** [comment]
I'm going to need more information if you want me to fix something

**Comment by zbx911** [comment]
can you test your pyUE4Parse in Mir4 pc? you can find some wrong ！
Mir 4 (mobile version)  0x86C7FF3309131F64AA1A2872444F3841281F7B82FEE14A54BF5CAD6C36F57377
Mir 4 (PC version)  0xAD768F68B8795A776100525791F675E15341D565D9AB4B4B74C95F31B03310F3

**Comment by MinshuG** [comment]
fixed Minshug/pyUE4Parse@8151cbd5ae92845cb858d335ad35744cdbe73e99
