### ISSUE TITLE
Fortnite UE5 

### ISSUE THREAD

**Issue by HybridFNBR** [MinshuG/pyUE4Parse#2]
![image](https://user-images.githubusercontent.com/68912574/144748766-f7b54ff4-e5f8-4a97-a56f-08c1a8b057b4.png)

**Comment by MinshuG** [comment]
fixed 1c1096e and I'll fix the package reading soon

**Comment by HybridFNBR** [comment]
👍

**Comment by HybridFNBR** [comment]
![image](https://user-images.githubusercontent.com/68912574/145691101-bf3391f1-352e-4730-b7a4-6162980d3ad9.png)
found a bug with that commit unless something has changed with the args 🤷‍♂️ 
forgot to mention lastweek 😳

**Comment by MinshuG** [comment]
https://github.com/MinshuG/pyUE4Parse/commit/c73b9b8934b0a01fcbb8cd3bc64f2cca56086aae fixed
