### ISSUE TITLE
[question]  Is there a way to recreate a .uasset/uexp file from a JSON file using UE4Parse?

### ISSUE THREAD

**Issue by Saipan0** [MinshuG/pyUE4Parse#24]
Hi,
First of all, thank you for your work.
I have extracted data from a .uasset and .uexp file and converted it into JSON format. Now, I want to recreate the files from this JSON data. I only found file reading functionality, but Does UE4Parse have any functionality that allows for writing or recreating .uasset files from JSON or other structured data?
If not, what would be the best approach to achieve this?

Thanks for your help!

**Comment by MinshuG** [comment]
no that's not possible. writing packages is not supported.
