### ISSUE TITLE
very stupid question

### ISSUE THREAD

**Issue by s1btea** [MinshuG/pyUE4Parse#8]
how i can use StreamedFileProvider to initialize Valorant pak files?

**Comment by MinshuG** [comment]
Register each pak using `StreamedFileProvider.initialize`

**Comment by s1btea** [comment]
But how i can get file stream from manifest? I tryed UEManifestReader (https://github.com/MinshuG/UEManifestReader), and there's goes nothing. Am i should write my own val manifest parser, or im missing something?

upd: im telling lie. im not tryed UEMR, i just can't understand how i can use it in this case
upd2: it throwing me a header read error

**Comment by MinshuG** [comment]
Riot manifest don't have same format as epic's that's why you are getting the error.
You have to write your own parser for manifest. [Morilli/ManifestDownloader](https://github.com/Morilli/ManifestDownloader) you can use this as reference or write a python binding for this.

**Comment by s1btea** [comment]
its time to skid xD
Thanks for help :)
